### ISSUE TITLE
Bookmarks missing in elasticsearch documentation

### ISSUE THREAD

**Issue by ashemedai** [mastodon/documentation#1005]
In https://github.com/mastodon/documentation/blob/fc99a8235873373296b8356bce59b9d82e149507/content/en/admin/optional/elasticsearch.md?plain=1#L10 its mentions toots, favourites, and mentions. It seems to be missing bookmarks. Unless I am fully mistaken, this works for me on bookmarks on mastodon.social.

Can someone with deeper knowledge of the system please adjust accordingly?

**Comment by trwnh** [comment]
Ah, bookmarks weren't a think when that bit was written -- added to https://github.com/mastodon/documentation/pull/991/commits/263350c53f00756c7add68cf5635889312b59130

**Comment by aaaaalbert** [comment]
(One of you might want to *close-as-implemented* this issue then :-)

**Comment by ashemedai** [comment]
Got added.
