### ISSUE TITLE
Install instructions reference https://github.com/tootsuite/mastodon.git

### ISSUE THREAD

**Issue by SamStephens** [mastodon/documentation#1010]
The install instructions reference https://github.com/tootsuite/mastodon.git, however the definitive home is https://github.com/mastodon/mastodon

**Comment by SamStephens** [comment]
Closed my pull request in favor of the thorough version, https://github.com/mastodon/documentation/commit/f5792aed48680c7494d57f422513f1d1228467b8 from @trwnh 

However @trwnh , this commit is not part of any branch? Does it need to be made into a pull request or rebased onto the master branch?

**Comment by trwnh** [comment]
It's part of #991 which is not merged yet but should be soon, I'd think?

**Comment by SamStephens** [comment]
@trwnh ah, apologies, I didn't realize it is possible to reference commits from an unmerged pull request from the destination repository like that, and I didn't know how to track it back to its containing pull request.

**Comment by SamStephens** [comment]
This will be resolved by https://github.com/mastodon/documentation/pull/991

**Comment by renchap** [comment]
Fixes in #991
