### ISSUE TITLE
How to log in as a user without using a browser?

### ISSUE THREAD

**Issue by y0shir** [mastodon/documentation#1014]
I was interested in writing a simple boost bot, but noticed that API documentations only talks about geting user token trough a browser. This makes it so that there is no way to run a bot on a headless server without unnecessary browser that exist only to log it. Is there truly no other way?

**Comment by tathamoddie** [comment]
This issues list is for the documentation itself (e.g. typos, broken links, or broken grammar). For general discussion, I think you want to head to the [main discussions area](https://github.com/mastodon/mastodon/discussions).

To answer your specific question though: Mastodon uses OAuth for API authentication. [The relevant documentation page](https://docs.joinmastodon.org/spec/oauth/) talks about how it supports multiple flows:

> Mastodon supports the following OAuth 2 flows:
> 
> Authorization code flow: For end-users
> Password grant flow: For bots and other single-user applications
> Client credentials flow: For applications that do not act on behalf of users

You could do one of:
1. Complete the authorization flow on your own machine, get the resultant token, then plug that into your bot. This saves you from ever storing your password on the headless server.
2. Use the password grant flow. This requires you keeping your password on the headless server.

Either way, you'll want to generally research OAuth flows, and how to do them in headless scenarios. This knowledge is not specific to Mastodon.

**Comment by trwnh** [comment]
If you want to, you can also log in manually and create a new application via Settings > Development, then copy-paste the generated access token into your config file or environment variables or whatever.
