### ISSUE TITLE
Add an `exclude` keywords list for search

### ISSUE THREAD

**Issue by KRRW** [mastodon/documentation#1015]
I think it will be very useful to provide an option to exclude certain keywords in addition to searching a keyword, both in the site and in the API. [Example: I would like to search for folks who are `gay` but exclude those who are posting `nsfw` content.] Might also be useful to be able to exclude (or perform exclusive search for) images, videos, audio, or to search for text-only statuses/toots.

**Comment by trwnh** [comment]
wrong repo? i think you meant to post this on https://github.com/mastodon/mastodon

**Comment by andypiper** [comment]
closing this as off-topic for the documentation, please raise against [the main project](https://github.com/mastodon/mastodon) if needed.
