### ISSUE TITLE
missing ruby version bump 3.0.3>3.0.4

### ISSUE THREAD

**Issue by rykzon** [mastodon/documentation#1027]
documentation installs ruby 3.0.3, latest release requires 3.0.4

**Comment by echox** [comment]
Since I had the same issue and I saw the pull request: will be fixed by https://github.com/mastodon/documentation/pull/1026

**Comment by fixermark** [comment]
Should this be 3.2.2 now? Looks like the `.ruby-version` file in the [main repo](https://github.com/mastodon/mastodon/blob/main/.ruby-version) is now calling for v3.2.2.

**Comment by tnonate** [comment]
> Should this be 3.2.2 now? Looks like the `.ruby-version` file in the [main repo](https://github.com/mastodon/mastodon/blob/main/.ruby-version) is now calling for v3.2.2.

This is correct accoridng to the latest release.

**Comment by aaaaalbert** [comment]
The current [live docs](https://docs.joinmastodon.org/admin/install/) ask for Ruby 3.2.2.

The version number was updated in commit e1b2a6b. I think this issue can be closed.

(CC: @vmstan since I notice you have been cleaning up old issues recently.)

**Comment by vmstan** [comment]
Yep, been sort of bouncing between getting the PRs merged and then closing out issues behind them, feel free to ping me on anything else you see. It's been... a task 😉
