### ISSUE TITLE
No client_secret in the request

### ISSUE THREAD

**Issue by dve** [mastodon/documentation#1033]
The doc mentions the client_secret but it's not needed in the request - and the user should not know it.

https://github.com/mastodon/documentation/blob/69e9017730131a3fbd2d92e65ea2a3de793fa0fc/content/en/client/authorized.md?plain=1#L38

**Comment by trwnh** [comment]
it's used in the request

**Comment by dve** [comment]
Yes, but in the next request `oauth/token` there is the note again and correct IMHO. But my comment is about the `oauth/authorize` request in which only the `client_id` is used

**Comment by trwnh** [comment]
Ohh, I see what you mean now
