### ISSUE TITLE
Clarify use of admin vs. owner roles in instance setup documentation

### ISSUE THREAD

**Issue by filmaj** [mastodon/documentation#1042]
Based on what I was able to find in #974 and #972, it seems like starting with v4.0.0, the role with the most permissions changed from being `admin` to being `owner`.

To describe my own personal situation: when I started setting up my own instance of Mastodon, the latest released version was 3.x. However, the live documentation for Mastodon mentions to use the `owner` role. Thus, when I followed the instructions [here](https://docs.joinmastodon.org/admin/setup/#admin), the command failed for me. Turns out I needed to use `admin`.

My suggestion: perhaps we could add a little callout note in https://docs.joinmastodon.org/admin/setup/#admin mentioning that this role name changed in v4, and to use `admin` in v3.x instead? Happy to send a PR.

**Comment by trwnh** [comment]
Fixed in https://github.com/mastodon/documentation/pull/991/commits/35fc91d111073c47425c1f8f4cd00af309f35836
