### ISSUE TITLE
docs for max characters / counting of characters

### ISSUE THREAD

**Issue by mooseyboots** [mastodon/documentation#1087]
is there any documentation for the maximum characters for user profile notes?

- is it always 500 chars or configurable?
- if configurable, can i fetch it from an instance?
- do URLs count the same way as in posts?

**Comment by trwnh** [comment]
500, not configurable. URLs should count the same way but I'm not 100% sure

**Comment by trwnh** [comment]
They do

**Comment by vmstan** [comment]
https://docs.joinmastodon.org/user/posting/#text
