### ISSUE TITLE
Some servers are not available here

### ISSUE THREAD

**Issue by ascendho** [mastodon/documentation#1089]
![image](https://user-images.githubusercontent.com/78126591/204417559-95a1aa59-f9c8-4a0f-b4c4-0183d7d076b8.jpeg
)
![image](https://user-images.githubusercontent.com/78126591/204417576-84b12151-27d0-4764-b9a2-fdb27d560d10.jpeg)

I am a little bit confused , why some servers are not available here? I can log in mastodon.lol, but mas.to and some other servers don’t work, are these blocked?  Could any one tell me how this work?

Location: mainland China

**Comment by trwnh** [comment]
Maybe -- it is possible that mainland China is blocking some domains. They would not be able to block any domain they are not aware of, though.

**Comment by ascendho** [comment]
Ok, another thing I want to wonder is whether different servers matter? I mean, I want to get more informed information, whether it differs between different servers, because obviously mastodon.social has the most users.> Maybe -- it is possible that mainland China is blocking some domains. They would not be able to block any domain they are not aware of, though.

**Comment by ascendho** [comment]
Thanks in advance.

**Comment by trwnh** [comment]
Your server matters somewhat -- bigger or older servers can have more already-discovered information. But you can follow anyone on any server as long as you know their URL or their address. It is like email.

**Comment by nightpool** [comment]
@ascendho The most important thing is that different servers are run by different people and have different users and different policies towards certain sorts of content. For example, one server might be run by LGBT users, while another might be run by programmers, and the admins of those servers are responsible for the moderation of all content posted on that server.

**Comment by ascendho** [comment]
Ok, thanks.
