### ISSUE TITLE
Add WebApe as a Mastodon VPS provider

### ISSUE THREAD

**Issue by tio-trom** [mastodon/documentation#1091]
Hello,

My name is Tio and on top of providing 20+ free services via https://trom.tf/ like Friendica, Peertube, Nextcloud and the like, I also have a project called WebApe https://webape.site/ where I provide full VPS servers that among other services, we provide Mastodon instances too. It is a year old and we already have a few subscribers for the Mastodon package.

If you think it is worth adding it to the documentation please do so https://github.com/mastodon/documentation/blob/master/content/en/user/run-your-own.md

Thanks!

**Comment by helix2301** [comment]
put this in as pull request to be approved

**Comment by tio-trom** [comment]
I hope I did it right https://github.com/mastodon/documentation/pull/1095 - thanks!
