### ISSUE TITLE
markers api doc: contradictory parameter description

### ISSUE THREAD

**Issue by hmsuchier** [mastodon/documentation#1105]
the documentation for [markers api](https://docs.joinmastodon.org/methods/markers/), `timeline` query parameter is documented as required, but the documentation also describe a "normal" behavior (returns an empty array, which seems to be the case in practice) instead of a 400 HTTP error that would be legit in the case of a missing required parameter.

**Comment by trwnh** [comment]
I marked it as "required" because it's required to get anything usable out of that endpoint. I'm not sure a strict interpretation regarding validation errors is the most useful thing in writing API documentation. I'd consider it a form of graceful failure.

**Comment by hmsuchier** [comment]
I understand. The fact that the "required" status for this parameter is as important as the one for the authorization one whose absence actually provokes a clear error, is somehow misleading. Maybe the point concerns the api itself, or maybe there is no point at all :)

**Comment by trwnh** [comment]
I suppose it doesn't really matter either way, so I can remove the "required" badge on the argument that if you request no markers, you will get no markers?

**Comment by hmsuchier** [comment]
Yes, possibly just a visual way (bold font) to stress that behavior? just a suggestion.

**Comment by trwnh** [comment]
added in #1060
