### ISSUE TITLE
nginx portion of install slightly broken

### ISSUE THREAD

**Issue by JMille34** [mastodon/documentation#1112]
Symptom: certbot fails to run, complains about certificate lines not being present (commented out). The docs say to uncomment the two lines after running certbot, but certbot won't run until you fix it.

My solution but probably not the right one:
1. Comment out the two "listen 443" lines
2. run certbot again successfully but it breaks the config
3. revert by copying the source file again from /home/mastodon/live/dist/nginx.conf to /etc/nginx/sites-available/mastodon
4. edit and uncomment the two certificate lines, fix the four instances of "example.com"
5. restart nginx

**Comment by robermar23** [comment]
Agreed.  Ran into this myself, following steps line by line.

The docs are broken.

**Comment by vmstan** [comment]
Should be fixed in current instructions.
