### ISSUE TITLE
Broken link to sanitize_config.rb

### ISSUE THREAD

**Issue by jwilk** [mastodon/documentation#1115]
<https://docs.joinmastodon.org/spec/activitypub/#sanitization> links to <https://github.com/mastodon/mastodon/blob/master/app/lib/sanitize_config.rb>, but the latter is 404.

**Comment by trwnh** [comment]
ah, looks like https://github.com/mastodon/mastodon/pull/15917 moved it from app/lib/sanitize_config.rb to lib/sanitize_ext/sanitize_config.rb -- the link should indeed be https://github.com/mastodon/mastodon/blob/main/lib/sanitize_ext/sanitize_config.rb
