### ISSUE TITLE
 some informations needed before start installing mastodon on my linux server(debian 10)

### ISSUE THREAD

**Issue by student-CE** [mastodon/documentation#1124]
Hi please , I need some informations before start installing mastodon on my linux server(debian 10)

after type the command used to run the script mastodon ( sudo -u mastodon RAILS_ENV=production bundle exec rake mastodon:setup)

1/ for the question : Do you want to send emails from localhost?

in case I have an account email on the smtp server address: smtp.ionos.de

in

SMTP password : should i type the password of my SMTP server "smtp.ionos.de " or the login password of my own email ID on this smtp server

Ps:The email ID, i use it on the smtp server "smtp.ionos.de"

2/for the question domain name:

when i have typed hostname -d , on my server linux i have found something like "server.something.net",

is it correct if i type another subdomain like "mastodon.test.net" and not "server.something.net"(domain found after typing the command hostname -d ) for the question domain name and then i will modify the same name of subdomain under /etc/nginx/sites-available/ and link it with mastodon.

**Comment by nightpool** [comment]
> SMTP password : should i type the password of my SMTP server "smtp.ionos.de " or the login password of my own email ID on this smtp server

I'm not sure I understand the distinction you're making or the question you're asking. You should use the password that you use to connect to this system for your email ID, over SMTP. I don't understand how the two options you provided are different. As an example, if you're using `gmail.com`, you would use an [App Specific Password](https://support.google.com/accounts/answer/185833?hl=en#) here to provide single-use access to the SMTP protocol.

You should direct further questions on how to connect to `smtp.ionos.de` to the provider/sysadmin for that server, we're not able to help you with them here.

> is it correct if i type another subdomain like "mastodon.test.net" and not "server.something.net"(domain found after typing the command hostname -d ) for the question domain name and then i will modify the same name of subdomain under /etc/nginx/sites-available/ and link it with mastodon.

As long as your server can receive traffic on `mastodon.test.net`, and the DNS records are updated appropriately, then this should be fine.

**Comment by student-CE** [comment]
Hi, thanks for your response
In case I will type **No** for the question  **Do you want to send emails from localhost?**

here is it required to setup the smtp server ("smtp.ionos.de") with postfix ? or the step of this question  is limited in enter "No" for the questions then fillout the 
 SMTP SERVER NAME,
 USERNAME SMTP,
Password SMTP

without setup this smtp server with postfix in the linux server ?
