### ISSUE TITLE
Install instructions are outdated

### ISSUE THREAD

**Issue by innosflew** [mastodon/documentation#1208]
Recently I had to set up like three different Mastodon instances on different servers. Every time I've followed the "[Installing from source](https://docs.joinmastodon.org/admin/install/)" guide to the letter and each time I have run into the same issues:

The first issue is at the "[Setting up nginx](https://docs.joinmastodon.org/admin/install/#setting-up-nginx)" and "[Acquiring a SSL certificate](https://docs.joinmastodon.org/admin/install/#acquiring-a-ssl-certificate)" part. When you try to set up certbot using the command from the guide it modifies your Nginx configuration that you've already set up in the previous step and causes it to fail. In order to avoid this you have to run `certbot` in `certonly` mode by using this command: `certbot certonly --nginx -d example.com` and only then copy the configuration template for nginx per the instructions, then uncomment the `ssl_certificate` and `ssl_certificate_key` lines in `/etc/nginx/sites-enabled/mastodon` and then restart nginx with `systemctl reload nginx`. This might have caused less experienced users to think they did something wrong (even though they followed the guide) and give up. From what I've seen [this issue has already been reported last year](https://github.com/mastodon/documentation/issues/940) but the guide is still the same.

The second issue I noticed at each install is that after I set everything up the site looks broken. I only see a white page with a black Mastodon logo somewhere and nothing else at all. The way I managed to fix this every time is by modifying the folder permissions of the main Mastodon folder and its subfolders to `775` using the `Chmod` command. As I've said this has happened at every installation even though I was installing on different computers, so this might also be worth mentioning in the guide.

**Comment by aaaaalbert** [comment]
Re file permissions: This is also reported in #1128, and a docs fix (with stricter dir access mode than yours) has been proposed and is linked there.

Makes me wonder which OS/flavor you are using. I'm looking at the user creation template, `/etc/adduser`, on a Ubuntu 22.04.2 LTS and a Raspbian/Debian Bullseye, and both have a default of `DIR_MODE=0755`.

**Comment by innosflew** [comment]
I'm using a Hetzner cloud server with Ubuntu 22.04.

**Comment by brookmiles** [comment]
The certbot instructions have been fixed with https://github.com/mastodon/documentation/pull/1036
