### ISSUE TITLE
API documentation of method to add a status to a filter group is missing parameter

### ISSUE THREAD

**Issue by bocops** [mastodon/documentation#1217]
Documentation of the method [Add a status to a filter group](https://docs.joinmastodon.org/methods/filters/#statuses-add) mentions a **filter ID** that is used as a path parameter, but doesn't mention any additional form parameters.

I assume that at least one form parameter identifying the status that supposedly gets added to the filter needs to exist. What is its definition?

**Comment by trwnh** [comment]
ah yeah, it does seem to be missing. the parameter is `status_id` https://github.com/mastodon/mastodon/blob/main/app/controllers/api/v2/filters/statuses_controller.rb

**Comment by andypiper** [comment]
Closed by #1312
