### ISSUE TITLE
An important parameter is missing from the API doc on editing a post

### ISSUE THREAD

**Issue by GreenFootballs** [mastodon/documentation#1239]
I'm working on a function to edit a Mastodon post, and could not find a way in the API documentation to  edit the ALT text attributes of images.

That section of the docs is [here.](https://docs.joinmastodon.org/methods/statuses/#edit)

I finally used the DevTools network tab to watch the API calls as I edited an image's description and discovered a parameter being passed that is not in the doc: `media_attributes`, an array of objects that look like this:

```
"media_attributes": [
    {
        "id": "110566601931157298",
        "description": "White priest: \"Without us you'd still be worshipping the sun!\"\n\nNative Americans: \"Dude... the sun is real\"",
        "focus": "0.00,0.00"
    }
]
```

The API doc does have a parameter for `media_ids`, but not `media-attributes`. And without using it there is no way to edit ALT text, a very common usage because people often forget to add it the first time they post.

**Comment by andypiper** [comment]
Closed in #1351
