### ISSUE TITLE
Missing documentation for Administration -> Roles functionality

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/documentation#1251]
The relatively new account roles setup that was added over the past few years hasn't been documented, this means that some folks are promoting people to "owner" role, just to gain "view_devops" permissions. Ideally we would have documentation with screenshots of the roles UI, information about how to create new roles, and set their permissions.

**Comment by liamstojanovic** [comment]
I've [begun work on this issue.](https://github.com/mastodon/documentation/commit/4c525586d8a19fe56c310ccbf429290e80773483) 

Changes so far include an overview and instructions for creating new roles. I'd like to add information about the default roles, including the base role (_Default permissions_) prior to submitting a PR.

While testing and documenting this feature, I came across a [bug related to role priority](https://github.com/mastodon/mastodon/issues/26256). The documentation regarding priority is sparse, so it warrants more manual testing + review of the ruby controller code.
