### ISSUE TITLE
Update documentation to include new full-text search keywords

### ISSUE THREAD

**Issue by quinncomendant** [mastodon/documentation#1325]
### Steps to reproduce the problem

The [Mastodon documentation for Search](https://docs.joinmastodon.org/user/network/#search) mentions “Admins may optionally install full-text search” but it doesn't list the new keyword operators that were added (`has:`, `is:`, `from:`, `before:`, etc).

### Expected behaviour

The documentation should contain all search parameters

### Actual behaviour

The documentation lacks this info

**Comment by vmstan** [comment]
Duplicate of #1286
