### ISSUE TITLE
NodeJS Needs Updating

### ISSUE THREAD

**Issue by tnonate** [mastodon/documentation#1339]
When attempting to install NodeJS on a new install (see [here](https://docs.joinmastodon.org/admin/install/#node-js)) it warns users that:

>   This script, located at https://deb.nodesource.com/setup_X, used to install Node.js is deprecated now and will eventually be made inactive.

>  Please visit the NodeSource distributions Github and follow the instructions to migrate your repo. https://github.com/nodesource/distributions

The documentation should be updated accordingly.

**Comment by vmstan** [comment]
Fixed by #1340
