### ISSUE TITLE
Suggestion: Rename default branch to "main"

### ISSUE THREAD

**Issue by aaaaalbert** [mastodon/documentation#1357]
[Mastodon](https://github.com/mastodon/mastodon) renamed its default branch to "main" a while ago. This follows a general trend whose background and rationale is explained, e.g., in [this GitHub write-up](https://github.com/github/renaming/blob/main/README.md).

I suggest to do the same for the documentation repo. The GitHub document linked above even contains a guide on  how to do that.

**Comment by andypiper** [comment]
Accepted, we should do this - we did this on the joinmastodon repo recently. We just need to ensure that changing the branch name does not affect the documentation auto deployment at the same time. Looking into this.

**Comment by andypiper** [comment]
@renchap I believe this requires `.github/workflows/deploy.yml` modified to target `main`. Do you have any other concerns or notes on such a change? Would be great to align with our other repositories.

**Comment by aaaaalbert** [comment]
Side note: Same goes for [this Gitlab CI file](https://github.com/mastodon/documentation/blob/master/.gitlab-ci.yml#L13). Also, some files in `layouts/` mention `master` in URLs ([1](https://github.com/mastodon/documentation/blob/master/layouts/index.html#L14), [2](https://github.com/mastodon/documentation/blob/master/layouts/partials/footer.html#L38), [3](https://github.com/mastodon/documentation/blob/master/layouts/_default/single.html#L14)).

I can send a PR for all of that (if it can wait until the end of the week or so.)

**Comment by andypiper** [comment]
I don’t *think* we use the Gitlab CI any more but I could be mistaken. Thanks for spotting the other instances of the branch name - we would definitely want to do those as well. Happy to review a PR later!

**Comment by renchap** [comment]
We do not rely on Gitlab CI anymore, this can be dropped.

I am all for switching to `main`, and I can do it once there is a PR ready with the changes you mentioned above.

**Comment by aaaaalbert** [comment]
Here we go: PR #1373

**Comment by renchap** [comment]
Thanks for the PR.

I renamed the branch, merged your PR, and fixed the Github Pages setup. Everything seems to be working on my end!

**Comment by aaaaalbert** [comment]
Great, my pleasure!
