### ISSUE TITLE
Verification information does not mention 1 MB response limit

### ISSUE THREAD

**Issue by cassidyjames** [mastodon/documentation#1401]
When encouraging accounts to get verified, I've seen more than once some get tripped up by the 1 MB response limit. We should probably clarify exactly what that limitation is.

**Comment by andypiper** [comment]
I am guessing that this is a limit on the size of the HTTP response returned when the URL to be verified is called by the Mastodon server? (I used to see something similar in relation to the Twitter Cards crawler breaking if the HTTP response contained a huge HTML document with tons of inline CSS and JS). Interesting! Yes, definitely worth adding this to the docs if so.

**Comment by cassidyjames** [comment]
Yep, I forget the exact details, but if it might be something like verification used to fail completely if the response was >1MB, but it was updated to truncate the response at 1MB and not fail outright? I'm not 100% sure.

You can actually see this failing here: https://mastodon-link-debugger.vercel.app/profile/@EndlessOS@floss.social

So adding a note here https://github.com/mastodon/documentation/blob/main/content/en/user/profile.md#link-verification-verification is probably a good idea?

https://github.com/mastodon/documentation/pull/1402
