### ISSUE TITLE
`HAHAHUGOSHORTCODE-s0-HBHB` on https://docs.joinmastodon.org/entities/DomainBlock

### ISSUE THREAD

**Issue by nikclayton** [mastodon/documentation#1487]
https://docs.joinmastodon.org/entities/DomainBlock (and possibly other pages) is displaying HAHAHUGOSHORTCODE-s0-HBHB.

Apparently this is an issue with Hugo shortcodes, but I'm not familiar enough with Hugo to debug further.

**Comment by ClearlyClaire** [comment]
This seems related to https://github.com/gohugoio/hugo/issues/7416

**Comment by aaaaalbert** [comment]
The `{{<optional>}}` Hugo shortcode appears in three files (per [code search](https://github.com/search?q=repo%3Amastodon%2Fdocumentation+%7B%7B%3Coptional%3E%7D%7D&type=code): [`DomainBlock`](https://github.com/mastodon/documentation/tree/main/content/en/entities/DomainBlock.md), [`Instance`](https://github.com/mastodon/documentation/tree/main/content/en/entities/Instance.md), and [`ScheduledStatus`](https://github.com/mastodon/documentation/tree/main/content/en/entities/ScheduledStatus.md)).

AFAICS, the difference is that for `DomainBlock`, the shortcode is part of a `###`-level heading and is included in the Table of Contents at the top of the page, whereas it is on level `####` or `#####` or not even part of a heading in the other files (and thus not pulled into the ToC).

According to the linked Hugo issue, the problematic instance should be modified to `{{%optional%}}`.

I can provide a PR, but I don't have the toolchain at hand so I cannot test the change.

**Comment by aaaaalbert** [comment]
Here you go.

Let me emphasize once more: I have **not** tested that patch!

**Comment by aaaaalbert** [comment]
(Afterthought: the build process for the docs website should probably grep the Hugo-built files for `HAHAHUGOSHORTCODE` and complain.)

**Comment by aaaaalbert** [comment]
For reference, [the Hugo docs](https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown) explain the different shortcodes.

My summary: `{{<` shortcodes are *not* rendered before being sent to the content renderer (causing the `HAHAHUGOSHORTCODE` issue) whereas `{{%` shortcode *are* – for the latter type, which the above PR puts into use, "[t]his means that the rendered output from a shortcode can be part of the page’s table of contents [...]"
