### ISSUE TITLE
Local hugo build

### ISSUE THREAD

**Issue by jhauga** [mastodon/documentation#1497]
Locally cloning and running either:

1. ` hugo `
2. ` hugo serve `

Will produce:

1. ` Error: add site dependencies: load resources: loading templates: "/path/to/documentation/source/layouts/partials/footer.html:38:1": parse failed: template: partials/footer.html:38: function "page" not defined `

**Comment by andypiper** [comment]
Apologies for this, I merged some updates that require a newer Hugo version. The GH Action now uses Hugo 0.130.0 which I think should help here.

**Comment by aaaaalbert** [comment]
FYI: I tried a local build with Hugo v0.131.0 (gohugoio/hugo@bfbee17) and this repo's current state (824c7217), which indeed works.

**Comment by jhauga** [comment]
Just checked out the action history (_Update deploy.yml (# 1496)_ ), and yeah - this looks good. My Linux distro doesn't have the latest Hugo version, and building from binaries is just - well I'm going to wait for my distro to get the latest release.
