### ISSUE TITLE
Installation documentation references nonexistent install methods

### ISSUE THREAD

**Issue by reederda** [mastodon/documentation#1498]
The current documentation for setting up a Mastodon server lists a "1-Click Install Image" from DigitalOcean. This image has been removed from the Marketplace, and is no longer an option for install. If this isn't a temporary removal, the option should be removed from the documentation to avoid confusion.

[Link to affected page](https://github.com/mastodon/documentation/blob/main/content/en/user/run-your-own.md?plain=1#L57)

**Comment by aaaaalbert** [comment]
(See also PR #1485 that proposes to remove the reference to DigitalOcean)

**Comment by jeffsikes** [comment]
I installed using the droplet a few months ago. If you do reinstate it, consider creating a newer version - the previous version was old enough I had to upgrade multiple times and through at least one critical security patch that wasn't included in the base install. I think 4.2.1 was the base install.

Consider waiting to build a new droplet until after 4.3 becomes stable?

**Comment by vmstan** [comment]
That's definitely something we need to do a better job at. The build scripts were rewritten in 4.2 to make that easy it's just still a manual process. Need to look at how to automate that process.

**Comment by oneiros** [comment]
I just merged the PR mentioned above that removes the outdated reference. We will revert that should it ever come back.
