### ISSUE TITLE
Install ruby right before "Installing the last dependencies"

### ISSUE THREAD

**Issue by Lastorder-DC** [mastodon/documentation#1522]
By executing `RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install` at mastodon source root directory, It will read from `.ruby-version` and Install proper version for mastodon.

No need to Install ruby before checking out source.

Pros]
1. No need to update document every time ruby version is updated(since It will read from `.ruby-version`)
2. If someone decided to use fork instead of mastodon, they no longer install outdated version if fork uses newer ruby version than mastodon.

Cons]
1. Nothing so far(ruby not needed at setting up db part)

**Comment by renchap** [comment]
Closing as this has been fixed in our latest version
