### ISSUE TITLE
Broken links from (at least) Status/#reblog

### ISSUE THREAD

**Issue by nikclayton** [mastodon/documentation#1523]
1. Open https://docs.joinmastodon.org/entities/Status/#reblog
2. You'll see

> ### reblog
> **Description:** The status being reblogged.
> **Type:** nullable Status or null
> **Version history:**
> 0.1.0 - added

3. Hover over (or click on) "Status" on the "Type:" line.
4. Observe the link destination is https://docs.joinmastodon.org/.

It should be a link to /entities/Status (i.e., the currently open page).

There may be other examples of this, I haven't checked.

**Comment by aaaaalbert** [comment]
> There may be other examples of this, I haven't checked.

As noted in the comment to my PR, I did check quickly (via `grep`) and found no other occurrences of an unpopulated link like this.
