### ISSUE TITLE
`Notification` entity `type` of `update` should clarify which interactions trigger this notification type

### ISSUE THREAD

**Issue by trwnh** [mastodon/documentation#1563]
https://github.com/mastodon/mastodon/blob/68c778294036d9cb6234277c513a13f34f085561/app/services/fan_out_on_write_service.rb#L89

right now (and unless we get feature requests to the contrary?) the `update` notification is only considered for people who reblogged the edited status.

https://docs.joinmastodon.org/entities/Notification/#type currently says:

> `update` = A status you interacted with has been edited

this should probably be edited to say

> `update` = A status you interacted with has been edited. Currently, we consider reblogs.

or even simpler:

> `update` = A status you reblogged has been edited

i suppose we can go with the simpler option for now and if it ever changes we can a) note that in the version history, b) switch to using the slightly more verbose description

**Comment by ClearlyClaire** [comment]
Fixed by #1564
