### ISSUE TITLE
Broken links to API calls

### ISSUE THREAD

**Issue by saper** [mastodon/documentation#752]
https://docs.joinmastodon.org/spec/oauth/ contains links to the methods

GET /oauth/authorize -> https://docs.joinmastodon.org/spec/methods/apps/oauth.md#authorize-a-user

POST /oauth/token -> https://docs.joinmastodon.org/spec/methods/apps/oauth.md#obtain-a-token

POST /oauth/revoke -> https://docs.joinmastodon.org/spec/methods/apps/oauth.md#revoke-token

trying all of them cause 404 error

They should probably point to https://docs.joinmastodon.org/methods/apps/oauth/ but there are no labels there...

(reported via https://discourse.joinmastodon.org/t/broken-link-in-api-docs-page/2514)

**Comment by aschrijver** [comment]
There are other broken links too, like: https://docs.joinmastodon.org/client/methods/apps/#create-an-application

Which is referred to from: https://docs.joinmastodon.org/client/token/

**Comment by trwnh** [comment]
The anchors were added by Gitbook when the documentation was being written there. After porting back to Hugo, the API method blocks had to be re-implemented with many shortcodes, and presumably this re-implementation is missing anchor generation...

**Comment by andypiper** [comment]
No longer valid; closing.
