### ISSUE TITLE
How to debug a production instance

### ISSUE THREAD

**Issue by xeruf** [mastodon/documentation#852]
I have set up my instance according to https://docs.joinmastodon.org/admin/install and configured the caddy web server with a Caddyfile I found: https://gist.github.com/yukimochi/bb7c90cbe628f216f821e835df1aeac1#file-caddyfile-caddy2

Everything seems fine, except when I try to visit my instance on the web, I get an error page. I couldn't find anything helpful in the logs, so I wanted to enable further debugging. https://docs.joinmastodon.org/admin/config talks about the `RAILS_ENV` variable, which can't be set in the .env-file - but how else can I change it? Simply recompile with a different setting, i.e. `RAILS_ENV=development bundle exec rails assets:precompile`?

**Comment by xerus2000** [comment]
related: document the purpose of `RAILS_ENV=test` - is it for running tests, or testing an instance before going into production?
i.e. is the order `test` - `development` - `production` or `development` - `test` - `production`?

**Comment by xerus2000** [comment]
`RAILS_LOG_LEVEL` from https://docs.joinmastodon.org/admin/config may also be relevant

**Comment by Gargron** [comment]
> related: document the purpose of `RAILS_ENV=test` - is it for running tests, or testing an instance before going into production?
> i.e. is the order `test` - `development` - `production` or `development` - `test` - `production`?

Test is for unit testing. Only production is for production.

**Comment by Gargron** [comment]
See: https://docs.joinmastodon.org/admin/troubleshooting/

**Comment by xerus2000** [comment]
@Gargron I looked there, but it does not specify any info about how to enable any kind of debug mode, and the default logs are not always sufficient.
