### ISSUE TITLE
Search V2 API set query param following=true  not working

### ISSUE THREAD

**Issue by JoeSteven** [mastodon/documentation#876]
hi there, I tried to get search results for following users, according to the documentation I set the query param following = true, but the response is the same as following = false.

here is my request url(the host address has been replaced):
https://mastodon.example/api/v2/search?q=no&type=accounts&limit=20&offset=0&following=true

please take a look at this issue, thanks!

**Comment by renchap** [comment]
Fixed by https://github.com/mastodon/mastodon/pull/25681
