### ISSUE TITLE
Unable to install Mastodon due to mimemagic changes

### ISSUE THREAD

**Issue by zylo-** [mastodon/documentation#877]
Hi, the documentation here: https://docs.joinmastodon.org/admin/install/ to install Mastodon fails because of changes to mimemagic repositories.

Are there any guides how to fix this?

**Comment by neurer** [comment]
The solution at https://github.com/tootsuite/mastodon/issues/16102#issuecomment-832275094 worked for me.

**Comment by hughrun** [comment]
Also some guidance on [the Mastodon discourse](https://discourse.joinmastodon.org/t/mimemagic-0-3-5-no-longer-available/3497/20) for fresh installs, which worked for me:

```
bundle config deployment false
bundle update mimemagic --minor
bundle config deployment true
```
