### ISSUE TITLE
Repository unmaintained

### ISSUE THREAD

**Issue by n0toose** [mastodon/documentation#939]
I tried to make a few pull requests as a result of Mastodon's recent media attention, in hopes that the quality of my work would progressively get better before I moved on to more complex topics.

After thinking about whether I should author a document explaining in single terms how Mastodon federates with other programs as well and submitting two pull requests (one after I was asked to do so directly by a member in the IRC), I looked through the backlog. One of them contains some changes that I made but was never noticed by the maintainers, another one contains instructions to make Mastodon "work on 20.04" from 2020 and a decent amount of useful changes (that took a lot of time for other people and that should definitely be a part of the documentation) were not even given even the slightest amount of attention. To reiterate: I am not salty because I did not get my change reviewed within 24 hours in a project with so many pull requests, but, as a person that just wants to make the software more accessible and contribute to its success, I really do not see why I should contribute any time and effort into this if it's going to be essentially "de facto" thrown away, unless if it is a minor improvement.

Despite recent arguments and changes as to how Mastodon presents itself over the past month, there has been no commit to the documentation throughout that time.

I opened this issue after bringing up my concern in the IRC. Can this repository be monitored more actively by someone, or can you at least warn people about this? It's really frustrating as a contributor, because it feels like their own time is being somewhat disrespected.

**Comment by jgillich** [comment]
I agree, there are many pull requests piling up and most of them look good enough to merge.

@Gargron Are there any members of the project that would be interested in maintaining the documentation? I also wouldn't mind volunteering but I'm new to this project, #987 being my only contribution so far.

**Comment by trwnh** [comment]
There is https://github.com/mastodon/documentation/pull/991 which should at least bring up most of the content to 4.0, but I assume the focus from the project team right now is on actually getting 4.0 released...

**Comment by jgillich** [comment]
Nice, that looks like a ton of work!

**Comment by n0toose** [comment]
Absolutely understandable for all of you to be super busy when everyone's migrating onto the Fediverse right now, but do let me know if you all end up being in a position where you have the capacity to support additional contributors.

[ However, I think that it is still important to mention once again that the documentation on Tor presents itself as a "one shoe fits all" (in the case, that can be both theoretically and possibly dangerous for users that actually exist), is heavily opinionated (and sometimes incorrect on that front)... ]

**Comment by trwnh** [comment]
Admittedly I spent the least time on the admin guides (installation, configuration, optional features, etc), so there's quite a bit of stuff in that section that's probably not as useful as it could be, yeah... and specifically for the bits about Tor, I'm not sure I know enough about the subject to be able to spot on my own what's wrong with it.

**Comment by n0toose** [comment]
I think this is getting out of the scope for this issue, but I remain available to answer any questions or send/revise/combine any PRs. I'm also willing to explain everything to a reviewer.

**Comment by vmstan** [comment]
We are working the backlog. I’m going to close this out because in the last two weeks we’ve merged or closed over 75 of them. Hopefully that’s being seen ❤️
