### ISSUE TITLE
Add firewall config for IPv6

### ISSUE THREAD

**Issue by noiob** [mastodon/documentation#945]
As it is now, [the documentation](https://github.com/mastodon/documentation/blob/master/content/en/admin/prerequisites.md#install-a-firewall-and-only-whitelist-ssh-http-and-https-ports) only includes rules for IPv4, which leaves v6 wide open. I'm not sure how to write them myself but I think it'd be useful to have an IPv6 analog considering it's 2022 and servers are starting to come with v6 addresses by default

**Comment by vmstan** [comment]
Closed by #1004
