### ISSUE TITLE
Do you have your hugo (?) theme published anywhere?

### ISSUE THREAD

**Issue by quintessence** [mastodon/documentation#973]
Hello! I am one of the admins for the hachyderm.io Mastodon instance. We wanted to write up some user documentation, CoC, etc. and wanted to use the Mastodon theme, if possible, so that it looked aligned with the experience that users have actually using Hachyderm. I was looking in your repo and it looks like you _might_ be using Hugo and so I was wondering if so, is the theme published where I can clone it and if not, what the best way to clone the theme is? (If all of that is acceptable to your license :) )

Thank you!

Quintessence

**Comment by trwnh** [comment]
Currently there is no theme -- it is using custom layouts defined directly in the `layout/` folder. If you wanted to copy those files into your own layout directory, you could quite possibly get them working that way. However, I think it may be better to switch to a proper theme at some point, although you'd have to see what @Gargron thinks about that. I was tentatively planning to make a PR switching over the documentation to a theme I developed specifically for https://docs.pixelfed.org -- it's currently in beta as I'm fixing some bugs, and there's nothing in the README to explain how to use it or which variables are available, but I hope to get around to it right after I send the PR to update the Mastodon docs to 4.0 (which I am going to do imminently).

**Comment by quintessence** [comment]
Thank you for taking the time to respond!

How firm are you on Pixelfied? No objections, just wondering if I should take a look at it or if the decision is still too early days :)

**Comment by trwnh** [comment]
It's a lil early, as the more important PR to make is the one that actually has the content for 4.0 😅

**Comment by quintessence** [comment]
Fair enough, thank you!
