### ISSUE TITLE
ubuntu suggested on preparing your machine page 

### ISSUE THREAD

**Issue by CyrilCommando** [mastodon/documentation#979]
ubuntu is suggested on preparing your machine page but ubuntu can't login as root without a bunch of tweaking so my question is why suggest it if you expect just a few pages later for a user to be logged in as root

**Comment by Rahelno** [comment]
While you can't login as root directly it is very common to execute commands as root or become root if you are a sudoer.

So, if you could execute things as root using sudo (e.g. sudo apt-get update) you are also able to become root by executing

su -
