### ISSUE TITLE
Links to V2 in media?

### ISSUE THREAD

**Issue by edent** [mastodon/documentation#981]
The current [media page](https://github.com/mastodon/documentation/blob/master/content/en/methods/statuses/media.md) says:

> 3.1.3 - deprecated in favor of POST `/api/v2/media`,

Is there documentation for V2? Should it be linked to from here?

**Comment by trwnh** [comment]
> which is equal to v1 in all aspects, except it returns HTTP 202

Calling the v2 media API is exactly the same as calling the v1 media API, just with a different route and different response.

**Comment by edent** [comment]
I see. I think. Should the V2 API be documented separately then?

**Comment by trwnh** [comment]
It could be, but it would be exactly the same as the v1 API endpoint, so pretty much everything would be duplicated and the only difference would be replacing the 1 with a 2.

**Comment by edent** [comment]
Thanks. In which case, if V2 is the same as V1, I'm not sure why I'd use it?  I guess I got confused because it said V1 was deprecated.

I might add some examples of the V2 responses then.

**Comment by trwnh** [comment]
Check https://github.com/trwnh/mastodocs if you'd like, I think I may have already done that

**Comment by andypiper** [comment]
I am pretty sure this is now resolved, but lmk if I'm mistaken.
