### ISSUE TITLE
The "rules" field on api/v1/instance is not documented

### ISSUE THREAD

**Issue by mcclure** [mastodon/documentation#988]
See: https://mastodon.social/api/v1/instance

There is a "rules" field in the JSON. As of version 20.0, the Tusky app depends on this field.

But see: https://docs.joinmastodon.org/methods/instance/

This field is not documented.

(The Tusky devs mentioned there may be other API fields that are not documented, and that should be fixed too, but this is the one I noticed.)

**Comment by trwnh** [comment]
It will be soon! Just need to send a PR from https://github.com/trwnh/mastodocs to this one 😓

**Comment by andypiper** [comment]
@trwnh is this something that could be cherry-picked over from your repo?
