### ISSUE TITLE
Scopes mismatch between oauth requests

### ISSUE THREAD

**Issue by ThomasFrans** [mastodon/documentation#995]
On this page, it says the scopes to obtain the actual token are a subset of the scopes in the request that register the application. I think this is a mistake, as this would allow the app to hide what it is actually doing in the oauth form displayed to the user... Shouldn't it be "a subset of the scopes that were used to ask permission from the user" from the request above?

https://docs.joinmastodon.org/methods/apps/oauth/

Scopes used to get permission from the user:
![image](https://user-images.githubusercontent.com/48214567/200892785-fc7895ea-e9c6-4d58-90c1-1cde17a874b2.png)

Possible mistake in the documentation:
![image](https://user-images.githubusercontent.com/48214567/200892466-89b87ec5-1bb8-456f-a1f8-640b84632a77.png)

**Comment by trwnh** [comment]
I think I see what you're saying... the confusion comes down to the fact that authorizing a user is optional. So the fix is to include another sentence saying something like "If `code` is provided, must be a subset of scopes requested from the user"

**Comment by trwnh** [comment]
> If `code` was provided, then this must be equal to the `scope` requested from the user. Otherwise, it must be a subset of `scopes` declared during app registration.

Fixed in https://github.com/mastodon/documentation/pull/991/commits/b1ddce526912d997bbd83957995e3456270da063
